import { spawnSync } from "node:child_process";
import { readdir, readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  FinanceBriefSchema,
  type ClaudeCliJsonEnvelope,
  type FinanceBrief,
} from "./types.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

/** Project root (one level up from the compiled `dist/` dir). */
export const ROOT = path.resolve(__dirname, "..");
// GitHub Pages serves the site from the `docs/` folder on the default branch.
export const OUTPUT_DIR = path.join(ROOT, "docs");
export const TEMPLATE_PATH = path.join(ROOT, "templates", "finance-brief.html");

/** Today as YYYY-MM-DD (UTC). */
export function todayIso(): string {
  return new Date().toISOString().slice(0, 10);
}

/** Parse a YYYY-MM-DD string into a UTC Date (avoids TZ off-by-one). */
function parseIsoDate(iso: string): Date {
  const [y, m, d] = iso.split("-").map(Number);
  return new Date(Date.UTC(y, m - 1, d));
}

/** Shift a YYYY-MM-DD date by `days` and return it as YYYY-MM-DD. */
export function addDays(iso: string, days: number): string {
  const d = parseIsoDate(iso);
  d.setUTCDate(d.getUTCDate() + days);
  return d.toISOString().slice(0, 10);
}

/**
 * The Monday (inclusive) that starts the Mon–Sun week containing `iso`. Daily
 * briefs are dated by their run day (Tue–Sat), each reporting the prior
 * session, so a Mon–Sat window captures the five dailies covering Mon–Fri
 * sessions.
 */
export function weekStartMonday(iso: string): string {
  const daysSinceMonday = (parseIsoDate(iso).getUTCDay() + 6) % 7; // Sun=0 -> 6, Mon=1 -> 0
  return addDays(iso, -daysSinceMonday);
}

/**
 * The Sunday (inclusive) that ends the Mon–Sun week containing `iso`. This is
 * the canonical key for a weekly wrap: the wrap for a given market week is
 * always filed under that week's Sunday, whether it was generated by the
 * Sunday job or manually earlier in the week.
 */
export function weekEndSunday(iso: string): string {
  return addDays(weekStartMonday(iso), 6);
}

/** The Friday of the Mon–Sun week containing `iso` (the last market session). */
export function weekFriday(iso: string): string {
  return addDays(weekStartMonday(iso), 4);
}

/** The three kinds of page this pipeline publishes. */
export type BriefKind = "daily" | "weekly" | "outlook";

/** Filename infix per kind — daily has none, the others are namespaced. */
const KIND_INFIX: Record<BriefKind, string> = {
  daily: "",
  weekly: "weekly-",
  outlook: "outlook-",
};

/** Short tag shown on a nav chip; dailies are unlabelled (they're the norm). */
export const KIND_NAV_LABEL: Record<BriefKind, string | undefined> = {
  daily: undefined,
  weekly: "Wrap",
  outlook: "Week ahead",
};

/** Basename (no extension) a brief of `kind` dated `iso` is stored under. */
export function briefBaseName(kind: BriefKind, iso: string): string {
  return `finance-brief-${KIND_INFIX[kind]}${iso}`;
}

/** One published page, as discovered on disk. */
export interface ArchiveEntry {
  /** The date this page is keyed by — Sunday for weekly, Monday for outlook. */
  date: string;
  kind: BriefKind;
  /** Page filename, relative to the output dir. */
  href: string;
}

/**
 * Load every persisted brief JSON of one kind from a dir, most-recent first.
 * The daily regex intentionally does NOT match the `weekly-`/`outlook-`
 * infixes, so those never pollute the daily archive or the dedup context.
 * Invalid files are skipped with a warning so one bad archive can't break a
 * rebuild.
 */
export async function loadBriefs(dir: string, kind: BriefKind): Promise<FinanceBrief[]> {
  const pattern = new RegExp(`^finance-brief-${KIND_INFIX[kind]}\\d{4}-\\d{2}-\\d{2}\\.json$`);
  const files = (await readdir(dir).catch(() => [] as string[])).filter((f) => pattern.test(f));

  const briefs: FinanceBrief[] = [];
  for (const file of files) {
    try {
      const raw = await readFile(path.join(dir, file), "utf-8");
      briefs.push(FinanceBriefSchema.parse(JSON.parse(raw)));
    } catch (err) {
      console.warn(
        `[finance-brief] skipping malformed ${kind} archive ${file}: ${err instanceof Error ? err.message : err}`,
      );
    }
  }
  return briefs.sort((a, b) => b.date.localeCompare(a.date));
}

/** Load the daily archive, most-recent first. */
export function loadArchivedBriefs(dir: string): Promise<FinanceBrief[]> {
  return loadBriefs(dir, "daily");
}

/**
 * Index every published page by date, most-recent first — the single source
 * the day-nav is built from. One chip per date: Tue–Sat carry a daily, Sunday
 * carries that week's wrap, Monday carries the week-ahead outlook. If a date
 * somehow has more than one kind, the weekly/outlook wins over the daily,
 * since those are the ones the nav is meant to surface on Sun/Mon.
 */
export async function listArchiveEntries(dir: string): Promise<ArchiveEntry[]> {
  const files = await readdir(dir).catch(() => [] as string[]);
  const byDate = new Map<string, ArchiveEntry>();
  // Daily first so a same-date weekly/outlook overwrites it, not the reverse.
  const kinds: BriefKind[] = ["daily", "outlook", "weekly"];

  for (const kind of kinds) {
    const pattern = new RegExp(`^finance-brief-${KIND_INFIX[kind]}(\\d{4}-\\d{2}-\\d{2})\\.json$`);
    for (const file of files) {
      const date = file.match(pattern)?.[1];
      if (date) byDate.set(date, { date, kind, href: `${briefBaseName(kind, date)}.html` });
    }
  }

  return [...byDate.values()].sort((a, b) => b.date.localeCompare(a.date));
}

/** Strips ```json fences if the model wraps its output despite instructions. */
export function stripCodeFence(raw: string): string {
  const trimmed = raw.trim();
  const fenced = trimmed.match(/^```(?:json)?\s*([\s\S]*?)\s*```$/);
  return fenced ? fenced[1] : trimmed;
}

/**
 * Condense a brief into a compact, model-readable summary (detail/why lines
 * only, not the full JSON) so a skill can see what was already published. Used
 * by the daily pipeline for dedup and by the weekly pipeline to feed the week.
 */
export function formatBriefForPrompt(brief: FinanceBrief): string {
  const lines: string[] = [];
  for (const section of brief.sections) {
    lines.push(`## ${section.label}`);
    for (const item of section.items) {
      lines.push(`- ${item.detail}${item.why ? ` (why: ${item.why})` : ""}`);
    }
  }
  if (brief.crossCuttingTheme) {
    lines.push(`## Cross-cutting theme`);
    lines.push(brief.crossCuttingTheme);
  }
  return lines.join("\n");
}

/** Total CLI invocations per run, i.e. one retry after the first failure. */
const CLAUDE_MAX_ATTEMPTS = 2;
/** Pause before retrying — long enough for a transient 529/429 spike to clear. */
const CLAUDE_RETRY_DELAY_MS = 60_000;

/** Block the (synchronous) pipeline without spawning a `sleep` subprocess. */
function sleepSync(ms: number): void {
  Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, ms);
}

/**
 * Invoke the Claude Code CLI with a prompt and return the parsed JSON envelope.
 * Both pipelines allow only WebSearch and expect a single strict-JSON result.
 *
 * A failed run is retried once. Transient API errors (529 Overloaded, 429) are
 * the dominant failure mode and nothing else revisits the gap: the next day's
 * run targets the next date and the skip-if-exists rule never comes back, so a
 * single blip used to mean a permanently missing page.
 */
export function runClaudeCode(prompt: string): ClaudeCliJsonEnvelope {
  for (let attempt = 1; ; attempt++) {
    try {
      return runClaudeCodeOnce(prompt);
    } catch (err) {
      if (attempt >= CLAUDE_MAX_ATTEMPTS) throw err;
      console.warn(
        `[finance-brief] claude attempt ${attempt}/${CLAUDE_MAX_ATTEMPTS} failed ` +
          `(${err instanceof Error ? err.message : err}); retrying in ` +
          `${CLAUDE_RETRY_DELAY_MS / 1000}s...`,
      );
      sleepSync(CLAUDE_RETRY_DELAY_MS);
    }
  }
}

function runClaudeCodeOnce(prompt: string): ClaudeCliJsonEnvelope {
  // NOTE: CLI flags occasionally change between Claude Code releases — run
  // `claude -p --help` to confirm these are current before relying on them
  // in production.
  const claudeArgs = [
    "-p",
    prompt,
    "--output-format",
    "json",
    "--allowedTools",
    "WebSearch",
    "--permission-mode",
    "acceptEdits",
    "--max-turns",
    "20",
  ];

  const result = spawnSync("claude", claudeArgs, {
    cwd: ROOT,
    encoding: "utf-8",
    maxBuffer: 1024 * 1024 * 32, // 32MB, search results can be verbose
    env: process.env,
  });

  if (result.error) {
    throw new Error(
      `Failed to launch "claude" CLI. Is @anthropic-ai/claude-code installed and on PATH? Original error: ${result.error.message}`,
    );
  }

  if (result.status !== 0) {
    throw new Error(
      `claude exited with status ${result.status}.\nstderr:\n${result.stderr}`,
    );
  }

  let envelope: ClaudeCliJsonEnvelope;
  try {
    envelope = JSON.parse(result.stdout);
  } catch (err) {
    throw new Error(
      `Could not parse claude CLI stdout as JSON. Raw stdout:\n${result.stdout}`,
    );
  }

  if (envelope.subtype !== "success") {
    throw new Error(
      `claude run did not succeed (subtype: ${envelope.subtype}). Full envelope:\n${JSON.stringify(envelope, null, 2)}`,
    );
  }

  return envelope;
}

/**
 * Parse + validate a Claude CLI result string into a FinanceBrief, tolerating
 * an accidental ```json fence around the object.
 */
export function parseBrief(rawResult: string): FinanceBrief {
  const jsonText = stripCodeFence(rawResult);
  let parsed: unknown;
  try {
    parsed = JSON.parse(jsonText);
  } catch (err) {
    throw new Error(
      `Skill output was not valid JSON after fence-stripping. Raw result:\n${jsonText}`,
    );
  }
  return FinanceBriefSchema.parse(parsed);
}

/**
 * Commit the regenerated site and push it to GitHub Pages. Enabled only when
 * FINANCE_BRIEF_PUBLISH=1 (the scheduled launchd job sets it) so manual/dev
 * runs don't push. Failures are logged and mark the run as failed via
 * process.exitCode, but never throw — the HTML is already written by this point.
 */
export function publishToGit(commitMessage: string): void {
  if (process.env.FINANCE_BRIEF_PUBLISH !== "1") {
    console.log(
      "[finance-brief] git publish skipped (set FINANCE_BRIEF_PUBLISH=1 to enable)",
    );
    return;
  }

  const git = (args: string[]) =>
    spawnSync("git", args, { cwd: ROOT, encoding: "utf-8", env: process.env });

  const add = git(["add", "docs"]);
  if (add.status !== 0) {
    console.error(`[finance-brief] git add failed:\n${add.stderr}`);
    process.exitCode = 1;
    return;
  }

  // Commit only if something is staged (`diff --cached --quiet` exits 1 when
  // there are staged changes).
  if (git(["diff", "--cached", "--quiet"]).status !== 0) {
    const commit = git(["commit", "-m", commitMessage]);
    if (commit.status !== 0) {
      console.error(`[finance-brief] git commit failed:\n${commit.stderr}`);
      process.exitCode = 1;
      return;
    }
    console.log("[finance-brief] committed website changes");
  } else {
    console.log("[finance-brief] no website changes to commit");
  }

  const push = git(["push", "origin", "master"]);
  if (push.status !== 0) {
    console.error(`[finance-brief] git push failed:\n${push.stderr}`);
    process.exitCode = 1;
    return;
  }
  console.log("[finance-brief] pushed to origin/master");
}
