import { access, mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import type { FinanceBrief } from "./types.js";
import { renderSite } from "./site.js";
import {
  OUTPUT_DIR,
  addDays,
  briefBaseName,
  formatBriefForPrompt,
  loadBriefs,
  parseBrief,
  publishToGit,
  runClaudeCode,
  todayIso,
  weekEndSunday,
  weekFriday,
  weekStartMonday,
} from "./lib.js";

// `/finance-brief-outlook` invokes the skill at
// .claude/skills/finance-brief-outlook/SKILL.md. The prior week's wrap (or, if
// there isn't one, its dailies) is appended at runtime as the starting point —
// see buildOutlookPrompt().
const PROMPT = process.env.FINANCE_BRIEF_OUTLOOK_PROMPT ?? "/finance-brief-outlook";

/**
 * Build the outlook prompt: the skill invocation, the Mon–Fri window it should
 * look forward to, and last week's closing picture so it can frame the setup
 * rather than start from a blank slate.
 */
function buildOutlookPrompt(
  monday: string,
  friday: string,
  lastWeek: FinanceBrief | undefined,
): string {
  const lines = [
    PROMPT,
    "",
    `THE WEEK AHEAD IS ${monday} (Monday) THROUGH ${friday} (Friday). Every`,
    "scheduled catalyst you name must fall inside that window — verify the date",
    "of each event by search before including it.",
  ];

  if (lastWeek) {
    lines.push(
      "",
      `LAST WEEK'S CLOSING PICTURE (published ${lastWeek.date}) — this is where`,
      "each market stands going in. Use it to frame the setup and the levels that",
      "matter; do not re-report it as news:",
      "",
      formatBriefForPrompt(lastWeek),
    );
  }

  return lines.join("\n");
}

async function exists(p: string): Promise<boolean> {
  return access(p).then(
    () => true,
    () => false,
  );
}

/**
 * Last week's closing picture: the prior week's wrap (the Sunday page) if one
 * was generated, otherwise its most recent daily — normally Saturday's, which
 * reports Friday's close. `loadBriefs` returns newest-first, so `find` picks
 * the latest match.
 */
async function loadLastWeekContext(monday: string): Promise<FinanceBrief | undefined> {
  const yesterday = addDays(monday, -1); // the Sunday that ended last week
  const priorWeekSunday = weekEndSunday(yesterday);
  const priorWeekMonday = weekStartMonday(yesterday);

  const wrap = (await loadBriefs(OUTPUT_DIR, "weekly")).find((w) => w.date === priorWeekSunday);
  if (wrap) return wrap;

  return (await loadBriefs(OUTPUT_DIR, "daily")).find(
    (b) => b.date >= priorWeekMonday && b.date <= priorWeekSunday,
  );
}

async function main() {
  const today = todayIso();
  // Keyed by the Monday of the week it looks forward to, so it owns the Monday
  // chip in the day-nav even if it is generated by hand on another day.
  const monday = weekStartMonday(today);
  const friday = weekFriday(today);
  const baseName = briefBaseName("outlook", monday);
  const jsonPath = path.join(OUTPUT_DIR, `${baseName}.json`);

  if (await exists(jsonPath)) {
    console.log(
      `[outlook-brief] outlook for the week of ${monday} already exists (${jsonPath}) — skipping. ` +
        `Delete that file to force a regeneration.`,
    );
    return;
  }

  const lastWeek = await loadLastWeekContext(monday);
  console.log(
    lastWeek
      ? `[outlook-brief] framing the week of ${monday}..${friday} against ${lastWeek.date}`
      : `[outlook-brief] no prior-week context found — running the week of ${monday}..${friday} cold`,
  );

  const envelope = runClaudeCode(buildOutlookPrompt(monday, friday, lastWeek));
  console.log(
    `[outlook-brief] claude run complete (cost: $${envelope.total_cost_usd ?? "?"}, turns: ${envelope.num_turns ?? "?"})`,
  );

  const brief = parseBrief(envelope.result);
  // The page's identity is the week it covers, not whatever date the model echoed.
  brief.date = monday;

  // Same ≤3-per-section contract as the weekly wrap, enforced defensively.
  for (const section of brief.sections) {
    if (section.items.length > 3) {
      console.warn(
        `[outlook-brief] ${section.label} returned ${section.items.length} items; trimming to 3.`,
      );
      section.items = section.items.slice(0, 3);
    }
  }

  await mkdir(OUTPUT_DIR, { recursive: true });
  await writeFile(jsonPath, JSON.stringify(brief, null, 2), "utf-8");
  console.log(`[outlook-brief] wrote ${jsonPath}`);

  // Re-render the whole site so the new Monday chip shows up everywhere and
  // index.html points at the outlook (the newest page).
  await renderSite();

  publishToGit(`Week-ahead outlook ${brief.date}`);
}

main().catch((err) => {
  console.error("[outlook-brief] FAILED:", err instanceof Error ? err.message : err);
  process.exitCode = 1;
});
