import { access, mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import type { FinanceBrief } from "./types.js";
import { renderSite } from "./site.js";
import {
  OUTPUT_DIR,
  briefBaseName,
  formatBriefForPrompt,
  loadArchivedBriefs,
  parseBrief,
  publishToGit,
  runClaudeCode,
  todayIso,
  weekEndSunday,
  weekStartMonday,
} from "./lib.js";

// `/finance-brief-weekly` invokes the skill at
// .claude/skills/finance-brief-weekly/SKILL.md. The week's daily briefs are
// appended at runtime — see buildWeeklyPrompt().
const PROMPT = process.env.FINANCE_BRIEF_WEEKLY_PROMPT ?? "/finance-brief-weekly";

/** Build the weekly prompt: skill invocation + this week's dailies, oldest first. */
function buildWeeklyPrompt(weekBriefs: FinanceBrief[]): string {
  const blocks = weekBriefs.map((b) =>
    [`DAILY BRIEF (published ${b.date}):`, "", formatBriefForPrompt(b)].join("\n"),
  );
  return [
    PROMPT,
    "",
    `THIS WEEK'S DAILY BRIEFS (${weekBriefs.length}, oldest first). Synthesize`,
    "these into the weekly wrap — at most 3 bullets per section. Do not simply",
    "concatenate them; distill the week's dominant threads:",
    "",
    blocks.join("\n\n---\n\n"),
  ].join("\n");
}

async function exists(p: string): Promise<boolean> {
  return access(p).then(
    () => true,
    () => false,
  );
}

async function main() {
  const today = todayIso();
  const monday = weekStartMonday(today);
  // A wrap is always filed under its week's Sunday, whoever generated it and
  // whenever — that's the slot the Sunday chip in the day-nav points at.
  const sunday = weekEndSunday(today);
  const baseName = briefBaseName("weekly", sunday);
  const jsonPath = path.join(OUTPUT_DIR, `${baseName}.json`);

  // The scheduled Sunday job is a no-op when the week's wrap was already
  // generated by hand earlier in the week — the manual one stays published and
  // we skip the ~$0.42 Claude run rather than overwrite it.
  if (await exists(jsonPath)) {
    console.log(
      `[weekly-brief] wrap for the week ending ${sunday} already exists (${jsonPath}) — skipping. ` +
        `Delete that file to force a regeneration.`,
    );
    return;
  }

  const archived = await loadArchivedBriefs(OUTPUT_DIR);
  // Dailies dated within this week's Mon..Sun window (ISO strings sort
  // lexically), oldest first so the model reads the week as a chronology.
  const weekBriefs = archived
    .filter((b) => b.date >= monday && b.date <= sunday)
    .sort((a, b) => a.date.localeCompare(b.date));

  if (weekBriefs.length === 0) {
    throw new Error(
      `No daily briefs found for the week of ${monday}..${sunday} in ${OUTPUT_DIR}. ` +
        `Run the daily pipeline first (npm run brief).`,
    );
  }
  console.log(
    `[weekly-brief] synthesizing ${weekBriefs.length} daily brief(s) from ${monday}..${sunday}: ` +
      weekBriefs.map((b) => b.date).join(", "),
  );

  const envelope = runClaudeCode(buildWeeklyPrompt(weekBriefs));
  console.log(
    `[weekly-brief] claude run complete (cost: $${envelope.total_cost_usd ?? "?"}, turns: ${envelope.num_turns ?? "?"})`,
  );

  const brief = parseBrief(envelope.result);
  // The page's identity is the week, not whatever date the model echoed back.
  brief.date = sunday;

  // Enforce the ≤3-items-per-section contract defensively (the skill is told
  // this, but the JSON schema doesn't cap it) so a chatty model can't produce
  // a bloated weekly page.
  for (const section of brief.sections) {
    if (section.items.length > 3) {
      console.warn(
        `[weekly-brief] ${section.label} returned ${section.items.length} items; trimming to 3.`,
      );
      section.items = section.items.slice(0, 3);
    }
  }

  await mkdir(OUTPUT_DIR, { recursive: true });

  // Weekly filenames carry a `-weekly-` infix so they never match the daily
  // archive regex in loadArchivedBriefs() — they stay out of the daily
  // archive and the daily dedup context.
  await writeFile(jsonPath, JSON.stringify(brief, null, 2), "utf-8");
  console.log(`[weekly-brief] wrote ${jsonPath}`);

  // Re-render the whole site so the new Sunday chip appears in every page's
  // day-nav, and index.html points at this wrap (the newest page).
  await renderSite();

  publishToGit(`Weekly finance brief ${brief.date}`);
}

main().catch((err) => {
  console.error("[weekly-brief] FAILED:", err instanceof Error ? err.message : err);
  process.exitCode = 1;
});
